version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Linting code..."
      - npm run lint
      - npm run test

  build:
    commands:
      - echo "Building React app..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
